export const content = {
  landing: {
    headline: "Ride perfect waves in warm water.",
    subheadline: "Discover our surf camp packages for all levels. Book your adventure in minutes.",
    cta: "Start Booking",
    reassurance: "Secure payment • Flexible dates • No hidden fees",
  },
  packageStep: {
    title: "Choose Your Surf Package",
    description: "Select a package that matches your surf level and goals.",
    surfLevelLabel: "Surf Level",
    surfLevelPlaceholder: "Select your level",
    surfLevelBeginner: "Beginner",
    surfLevelIntermediate: "Intermediate",
    surfLevelAdvanced: "Advanced",
    packageLabel: "Available Packages",
  },
  dateStep: {
    title: "Pick Your Arrival Date",
    description: "Choose an available start date for your surf camp.",
  },
  roomStep: {
    title: "Select Your Room",
    description: "Pick a room that fits your group size and preferences.",
    capacityLabel: (cap: number) => `Up to ${cap} guests`,
  },
  travellerStep: {
    title: "Traveller Details",
    description: "Tell us who’s coming. We need names for all guests.",
    peopleLabel: "Number of Travellers",
    travellerNameLabel: (i: number) => `Traveller ${i} Name`,
  },
  extrasStep: {
    title: "Add Extras",
    description: "Enhance your stay with add-ons and travel insurance.",
    addOnsLabel: "Optional Add-Ons",
    insuranceLabel: "Add travel insurance (15% of subtotal)",
    insuranceNote: "Covers trip cancellation, medical emergencies, and more.",
  },
  paymentStep: {
    title: "Payment",
    description: "Secure your spot with a deposit or pay in full.",
    paymentTypeLabel: "Payment Option",
    depositLabel: "Pay-Now Deposit (25%)",
    fullLabel: "Pay-In-Full",
    forceFullPaymentNote: "Full payment required for arrivals within 35 days.",
    formLabel: "Card Payment Form",
    payNow: "Pay Now",
    processing: "Processing...",
    error: "Payment failed. Please try again.",
  },
  confirmation: {
    title: "Thank You for Booking!",
    description: "Your surf adventure is confirmed. We can’t wait to see you.",
    bookingIdLabel: "Booking ID",
    packageLabel: "Package",
    roomLabel: "Room",
    arrivalLabel: "Arrival Date",
    travellersLabel: "Travellers",
    totalLabel: "Total Paid",
    notFoundTitle: "Booking Not Found",
    notFoundMessage: "Sorry, we couldn’t find your booking.",
    footer: "A confirmation email has been sent. Questions? Contact us anytime.",
  },
  summary: {
    sidebarLabel: "Booking Summary",
    title: "Your Booking",
    packageLabel: "Package",
    arrivalLabel: "Arrival",
    roomLabel: "Room",
    travellersLabel: "Travellers",
    addOnsLabel: "Add-Ons",
    insuranceLabel: "Insurance",
    paymentTypeLabel: "Payment",
    depositLabel: "Deposit",
    fullLabel: "Full",
    forceFullPaymentNote: "Full payment required for arrivals within 35 days.",
    totalLabel: "Total",
    priceNote: "All prices in EUR. Taxes included.",
    notSelected: "Not selected",
    none: "None",
    yes: "Yes",
    no: "No",
  },
  progressBar: {
    ariaLabel: "Checkout Progress",
    step1: "Package",
    step2: "Dates",
    step3: "Room",
    step4: "Travellers",
    step5: "Extras",
    step6: "Payment",
  },
  errorSummary: {
    label: "Error:",
  },
  datePicker: {
    label: "Arrival Date",
    loading: "Loading available dates...",
    placeholder: "Select a date",
    soldOut: "Sold Out",
  },
  validation: {
    packageRequired: "Please select a package and surf level.",
    dateRequired: "Please select an arrival date.",
    roomRequired: "Please select a room.",
    roomCapacity: "Selected room does not fit your group size.",
    travellerRequired: "Please enter the number of travellers.",
    travellerNameRequired: (i: number) => `Please enter a name for traveller ${i}.`,
  },
  cta: {
    next: "Next",
    back: "Back",
  },
}; 